# Generated by Django 4.2.5 on 2023-09-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
    ]
