# Generated by Django 4.2.5 on 2023-09-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Описание'),
        ),
    ]
